### ISSUE TITLE
[Bug Report] Minigrid environment fails to step when SymbolicObsWrapper is used

### ISSUE THREAD

**Issue by zidanwang2025** [Farama-Foundation/Minigrid#278]
**Describe the bug**

The Minigrid environment fails to step when SymbolicObsWrapper is used. 

**Code example**
```
import gymnasium as gym
from minigrid.wrappers import RGBImgObsWrapper, SymbolicObsWrapper, ImgObsWrapper
env = gym.make('MiniGrid-Empty-8x8-v0')
env = SymbolicObsWrapper(env)
obs, info = env.reset()
count = 0
for i in range(10000):
    action = env.action_space.sample()
    next_obs, reward, terminated, truncated, info = env.step(action)
    if (next_obs['image'] != obs['image']).any():
        count += 1
        obs = next_obs
print(count)
```
 
The ```count``` I got from this code is 0. While ```next_obs['direction']``` changes,``` next_obs['image']``` stays the same when env.step(action) is called. This does not happen when ```RGBImgObsWrapper(env)``` is used instead. 

**System Info**
 * `minigrid` was installed using _pip install minigrid_. 
 * macOS Monterey Version 12.3.1 is used. 
 * Python 3.8 is used. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by rodrigodelazcano** [comment]
Thank you for finding this, I got to replicate it and I'll fix it soon.

**Comment by rodrigodelazcano** [comment]
@zidanwang2025 
UPDATE: the wrapper is actually correct. The issue is that the encoded observation doesn't include the agent, and the map is static. If you try your code with a dynamic environment like `MiniGrid-Dynamic-Obstacles-5x5-v0` you'll find that the Symbolic observation is different. 

However, I'll modify the wrapper to include the agent in order to have the complete state of the environment.

**Comment by zidanwang2025** [comment]
Thanks for the update!!
