### ISSUE TITLE
[Question] What do you mean by "done" action in the action space?

### ISSUE THREAD

**Issue by kbkartik** [Farama-Foundation/Minigrid#395]
The documentation doesn't mention the following things:

1) What does "done" action stands for?

2) Where do we check the termination conditions for each of the environments?

**Comment by pseudo-rnd-thoughts** [comment]
1. Done is only used in two environments - "go to door" and "go to object" to signal that the agent thinks the task is complete. Otherwise the environment should ignore it

2. The documentation for each environment has a section called termination providing the different cases - https://minigrid.farama.org/environments/minigrid/

**Comment by NaphatPRM** [comment]
Can I further ask for the termination of the "go to object"? It says that it'll be terminated from "The agent stands next the correct door performing the done action." What does it mean?

**Comment by Roihn** [comment]
You may check this part of code to better understand the terminate condition:

https://github.com/Farama-Foundation/Minigrid/blob/9dbdf612351822fadc6a8a4d1c7519043bd9a1de/minigrid/envs/gotoobject.py#L156

I guess the `stands next the correct door` is a typo, which should be `the correct object` in this task.

To briefly explain, if the agent takes the "done" action, the environment will check if the agent is nearby the target object (its up, down, left, or right side, no need to face towards the object in this task). If yes, then give a positive reward (`self._reward()`) and set `terminated=True`. Otherwise, only setting `terminated=True` without updating the reward.
